name: ⚡️ 通知 Cloudflare 更新博客

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 发送部署请求
        run: curl -X POST "${{ secrets.CF_PAGES_DEPLOY_HOOK }}"
